name: autt

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - os: macos-15
            target: x86_64-apple-darwin
            BUILD_TARGET: release
          - os: macos-15-aarch64
            target: aarch64-apple-darwin
            BUILD_TARGET: release
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: add x86 target
        run: rustup target add x86_64-apple-darwin
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }} --target=${{ matrix.target }}
      #- name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
      #  run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: autt-${{ matrix.target }}
          path: target/${{ matrix.target }}/${{ matrix.BUILD_TARGET }}/autt
