name: autt

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        os: [macos-15, macos-15-aarch64]
        BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      #- name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
      #  run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: autt-${{ matrix.os }}
          path: target/${{ matrix.BUILD_TARGET }}/autt
